name: Deploy poudlard_timetable to Surge

on:
  push:
    branches:
      - master

concurrency:
  group: "surge"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projet/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Run the tests
        run: npm run test
      - name: Install Surge CLI
        run: npm install --global surge
      - name: Deploy
        run: surge --project ./dist --domain wheres-going-fethi.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        